version: 2.1

jobs:
  # Linux
  py27_linux:
    docker:
      # nox got requires python 3 but it can test 2.7
      - image: cimg/python:3.6
    steps:
      - checkout
      - run: apt-get update && apt-get install -y expect
      - run: echo 'export NOX_PYTHON_VERSIONS=2.7' >> $BASH_ENV
      - run: pip install nox
      - run: nox

  py36_linux:
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - run: apt-get update && apt-get install -y expect
      - run: echo 'export NOX_PYTHON_VERSIONS=3.6' >> $BASH_ENV
      - run: pip install nox
      - run: nox

  py37_linux:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - run: apt-get update && apt-get install -y expect
      - run: echo 'export NOX_PYTHON_VERSIONS=3.7' >> $BASH_ENV
      - run: pip install nox
      - run: nox

  # Misc
  coverage:
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - run: pip install nox
      - run: nox -s coverage

workflows:
  build:
    jobs:
      - py27_linux
      - py36_linux
      - py37_linux
